### ISSUE TITLE
include options in download

### ISSUE THREAD

**Issue by leytpapas** [AllaliAdil/Manga-Downloader-Extension#12]
It would be great to have a button to either download all pdf(s) at once without prompting every time. I could also save it as a preference but for every other file, I wouldn't want that, so that's not an option.
The same goes for downloading zips.
A clean solution would be to prepare a zip with everything the user adds and download this single file

**Comment by AllaliAdil** [comment]
some mangas have a lot of chapters, so the size of all chapters will be big (1GB or more).
browsers can't handle large files (it will freeze).

-you could save it as a preference then reset it when you finish.
-use another browser that you don't use a lot, so you don't have to worry about other files.

P.S
  I am not an advanced developer, and I am not willing to spend too much time on it.
