### ISSUE TITLE
Some websites aren't working

### ISSUE THREAD

**Issue by RiazCulture** [AllaliAdil/Manga-Downloader-Extension#13]
1stkissmanga doesn't work, it can't fetch images
manhuaus downloads blank documents
also mangakakalot and manganelo seem to take a long time till we can use the batch download

**Comment by AllaliAdil** [comment]
for 1stkissmanga and manhuaus
I fixed the issue in version 3.10.8

for manganelo and mangakakalot, it has to get(fetch) images page by page
or you will get too mush requests.
