### ISSUE TITLE
Unable to download some TOG episodes on WebToon

### ISSUE THREAD

**Issue by curiosport** [AllaliAdil/Manga-Downloader-Extension#14]
https://www.webtoons.com/es/fantasy/tower-of-god/list?title_no=1718&page=46

The following episodes I can't download the zip version, it only works with PDF:
75, 193, 210,211, 212, 219, 221, 229,230

If I am not mistaken, I noticed that the download does take place but when it is finished it is not saved on the disk.

On the other hand, can't you create a kind of cache? every time I reload the page the "Batch Download" option rescan the whole page from the beginning.

**Comment by AllaliAdil** [comment]
Sorry, but I am not an advanced developer.
and I am not willing to spend more time on adding new stuff.
I can only fix issues.

for the zip issue, I don't really know what's the problem.
I will fix it, if I find the problem.
