### ISSUE TITLE
Manganato site not fetching images

### ISSUE THREAD

**Issue by thelazypotato** [AllaliAdil/Manga-Downloader-Extension#18]
On chrome the extension keeps dropping unable to fetch images on manganato on any and all mangas i try to download. Thanks for the awesome extension tho, it rocks.

**Comment by AllaliAdil** [comment]
Please make sure you are using Chrome 80 or less / Firefox 86 or less 
(https://github.com/AllaliAdil/Manga-Downloader-Extension/tree/main/Browsers)
