### ISSUE TITLE
https://manga4life.com/ (Can't fetch image)

### ISSUE THREAD

**Issue by Gitthub335** [AllaliAdil/Manga-Downloader-Extension#6]
Hi, could you please fix the support for manga4life, it shows the error massage "(Manga Downloader) Can't fetch image.". I am using firefox and it was working just fine two weeks ago. I hope you can fix this soon, would really appreciate it.

**Comment by AllaliAdil** [comment]
Some images are hosted on websites where the extension doesn't have permission to access them.
I add permissions in version 3.8.2
