### ISSUE TITLE
Chapter download issues - Mangae Nelo

### ISSUE THREAD

**Issue by SeanFranklin** [AllaliAdil/Manga-Downloader-Extension#9]
I'm having some issues with select chapters on Manga Nelo.

https://manganelo.com/manga/st922886 (Dragon Ball Full Color)
For at least chapter 1-5 I'm getting:
```
(Manga Downloader) Can't fetch image.
https://bu3.mkklcdnv6tempv2.com/mangakakalot/d2/dragon_ball_full_color_edition/vol1_chapter_1_bloomers_and_son_goku/1.jpg
```
I skipped to chapter 81 and there is no problem with the download. I'm guessing it has to do with names/path not being formatted properly on some chapters.

Browser is Firefox 85.0.2 (64-bit)

Thanks for all your hard work on this project!

----------------------

On a side note, mangatail.me is listed on the supported websites, but it is a redirect to mangasaki.com. It doesn't look like mangasaki is supported, as no download links show up.
https://www.mangasaki.com/manga/dragon-ball-full-color-edition

**Comment by AllaliAdil** [comment]
you are downloading chapters from server 2, which the images are hosted on "mkklcdnv6tempv2.com"
but the extension does not have the permission to access

I added in version 3.10.0:
-permission to access where the images are hosted
-support to mangasaki.com
